#PBS -N chemifrac
# request the queue (enter the possible names, if omitted, serial is the default)
#PBS -q long8gb
# request 1 node
#PBS -l nodes=1
# request 72 hours and 30 minutes of cpu time
#PBS -l cput=72:30:00        
#PBS -e /home/mortonjt/Documents/chemifrac/jobs/chemifrac_long_error.txt
#PBS -o /home/mortonjt/Documents/chemifrac/jobs/chemifrac_long_output.txt

cd $PBS_O_WORKDIR
cd ~/Documents/chemifrac
source ~/.bashrc
source activate bio
source env.sh
cd ~/Documents/chemifrac/scripts
python chemifrac.py