#PBS -N chemifrac
# request the queue (enter the possible names, if omitted, serial is the default)
#PBS -q med8gb
# request 1 node
#PBS -l nodes=1
# request 72 hours and 30 minutes of cpu time
#PBS -l cput=72:30:00        
#PBS -e /home/mortonjt/Documents/chemifrac/jobs/chemifrac_graph_error.txt
#PBS -o /home/mortonjt/Documents/chemifrac/jobs/chemifrac_graph_output.txt
#PBS -M jmorton@eng.ucsd.edu

cd $PBS_O_WORKDIR
cd ~/Documents/chemifrac
source ~/.bashrc
source activate bio
source env.sh
cd ~/Documents/chemifrac/scripts
python chemifrac.py